steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '--build-arg=COMMIT=$COMMIT_SHA',
        '--build-arg=REPO=$REPO_NAME',
        '--build-arg=BRANCH=$BRANCH_NAME',
        '-t',
        'gcr.io/world-fishing-827/github.com/globalfishingwatch/$REPO_NAME:$COMMIT_SHA',
        '-t',
        'gcr.io/world-fishing-827/github.com/globalfishingwatch/$REPO_NAME:$BRANCH_NAME',
        '-t',
        'gcr.io/world-fishing-827/github.com/globalfishingwatch/$REPO_NAME:latest',
        '.',
      ]
 
  # Push production image to GCR
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'gcr.io/world-fishing-827/github.com/globalfishingwatch/$REPO_NAME:$COMMIT_SHA',
      ]


images:
  - 'gcr.io/world-fishing-827/github.com/globalfishingwatch/$REPO_NAME:latest'
  - 'gcr.io/world-fishing-827/github.com/globalfishingwatch/$REPO_NAME:$COMMIT_SHA'
  - 'gcr.io/world-fishing-827/github.com/globalfishingwatch/$REPO_NAME:$BRANCH_NAME'

timeout: 900s
