steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '--build-arg=COMMIT=$COMMIT_SHA',
        '--build-arg=REPO=$REPO_NAME',
        '--build-arg=BRANCH=$BRANCH_NAME',
        '--build-arg=TAG=$TAG_NAME',
        '-t',
        '${_BASE_IMAGE_NAME}:$COMMIT_SHA',
        '-t',
        '${_BASE_IMAGE_NAME}:$TAG_NAME',
        '-t',
        '${_BASE_IMAGE_NAME}:latest',
        '.',
      ]

images:
  - '${_BASE_IMAGE_NAME}:${TAG_NAME}'
  - '${_BASE_IMAGE_NAME}:${$COMMIT_SHA}'
  - '${_BASE_IMAGE_NAME}:latest'

timeout: 900s
substitutions:
  _BASE_IMAGE_NAME: 'gcr.io/${PROJECT_ID}/${REPO_NAME}/${BRANCH_NAME}'
options:
  dynamic_substitutions: true
