services:
  gcloud:
    image: google/cloud-sdk:latest
    volumes:
      - "gcp:/root/.config/"
    entrypoint: gcloud

  dev:
    build:
      context: .
      target: dev
    ports:
      - "10110:10110/udp"
    volumes:
      - ".:/opt/project"
      - "gcp:/root/.config/"
    entrypoint: /bin/sh

  test:
    # Runs tests using the production Docker image.
    # Intended to be executed in the GitHub CI environment.
    build:
      context: .
      target: test
    ports:
      - "10110:10110/udp"
    entrypoint: "pytest -v"

volumes:
  gcp:
    external: true
