services:
  receiver:
    build:
      context: .
      target: dev
    ports:
      - "10110:10110/udp"
    volumes:
      - ".:/opt/project"
      - "gcp:/root/.config/"
    entrypoint:  [ "socket-listener", "receiver", "--no-rich-logging" ]

  gcloud:
    image: google/cloud-sdk:latest
    entrypoint: gcloud
    volumes:
      - "gcp:/root/.config/"

  dev:
    entrypoint: /bin/sh
    build:
      context: .
    volumes:
      - ".:/opt/project"
      - "gcp:/root/.config/"

volumes:
  gcp:
    external: true
