[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["ais_listener"]

[project]
name = "gfw-ais-listener"
version = "0.1.0"
description = "A TCP/UDP service that receives NMEA-encoded AIS messages and writes them to sharded files in GCS'."
readme = "README.md"
license = { file = "LICENSE" }
authors = [
    { name = "Paul Woods.", email = "paul@globalfishingwatch.org"},
]
maintainers = [
    { name = "Paul Woods.", email = "paul@globalfishingwatch.org"},
    { name = "Tomás J. Link", email = "tomas.link@globalfishingwatch.org" },
]
classifiers = [
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
]
requires-python = ">= 3.9"
dependencies = [
    "ais-tools @ https://codeload.github.com/globalfishingwatch/ais-tools/tar.gz/v0.1.7.dev3",
    "cloudpathlib[gs]~=0.20",
    "pyyaml~=6.0"
]

[project.scripts]
gfw-ais-listener = "ais_listener.main:main"

[project.urls]
Homepage = "https://github.com/GlobalFishingWatch/ais-listener"
