[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["ais_listener"]

[project]
name = "ais-listener"
version = "0.1.0"
description = "A TCP/UDP service that receives NMEA-encoded AIS messages and writes them to sharded files in GCS'."
readme = "README.md"
license = { file = "LICENSE" }
authors = [
    { name = "Paul Woods.", email = "paul@globalfishingwatch.org"},
]
maintainers = [
    { name = "Paul Woods.", email = "paul@globalfishingwatch.org"},
    { name = "Tomás J. Link", email = "tomas.link@globalfishingwatch.org" },
]
classifiers = [
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]
requires-python = ">= 3.9"
dependencies = [
    "cloudpathlib[gs]~=0.20",
    "pyyaml~=6.0",
    "rich~=13.9",
    "rich-argparse~=1.6",
]

[project.scripts]
ais-listener = "ais_listener.cli:main"

[project.urls]
Homepage = "https://github.com/GlobalFishingWatch/ais-listener"
