sources:
  -
    source: 'ais-listener'
    protocol: UDP
    port: 10110
  -
    source: 'udp-other'
    protocol: UDP
    port: 10111
  -
    source: 'tcp-local'
    protocol: TCP
    host: 127.0.0.1
    port: 10100
    connect_string: "Connect"
  -
    source: 'kystverket'
    protocol: TCP
    host: 153.44.253.27
    port: 5631

